services:
  form-manager-app:
    container_name: form-manager-app
    build:
      context: .
      dockerfile: Dockerfile.dev
      # dockerfile: Dockerfile » prodcution dockerfile
    ports:
      - "8080:8080"
    volumes:
        - .:/app

