services:
  form-manager-app:
    container_name: form-manager-app
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GO111MODULE=on
    command: go run main.go
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /app
        - action: rebuild
          path: ./go.mod



