services:
  form-manager-app:
    container_name: form-manager-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - GO111MODULE=on
    # command: air -c .air.toml
    volumes:
        - .:/app




